specVersion: 0.0.1
description: ""
repository: ""
schema: ./schema.graphql
network:
  # endpoint: wss://polkadot.api.onfinality.io/public-ws
  endpoint: wss://parachain.staging.litentry.io
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  types:
    {
      Address: "MultiAddress",
      LookupSource: "MultiAddress",
      Account: { nonce: "U256", balance: "U256" },
      Transaction:
        {
          nonce: "U256",
          action: "String",
          gas_price: "u64",
          gas_limit: "u64",
          value: "U256",
          input: "Vec<u8>",
          signature: "Signature",
        },
      Signature: "[u8; 65]",
      BlockWeights: "u64",
      BlockLength: "u64",
      ParachainInherentData: "u64",
      DataSource: "u64",
      EthAddress: "[u8; 20]",
      QueryKey: "u64",
      ClassId: "u32",
      ClassIdOf: "ClassId",
      TokenId: "u64",
      TokenIdOf: "TokenId",
      Properties: { _enum: ["None","Transferable", "Burnable","Both"] },
      HashByte32: "[u8; 32]",
      CID: "Vec<u8>",
      ClassType:
        { _enum: { 1: "u32", 2: "HashByte32", 3: "(CID, CID, bool)" } },
    }
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
